env:
  - ORG_GRADLE_PROJECT_JAVA_7=openjdk7
  - ORG_GRADLE_PROJECT_JAVA_8=oraclejdk8
  - ORG_GRADLE_PROJECT_JAVA_9=oraclejdk9
  - ORG_GRADLE_PROJECT_JAVA_11=openjdk11
  global:
    - TIMEOUT=5000
      
addons:
  hosts:
    - localhost

language: java
install: true

script:
  - ./gradlew build
jdk:
  - oraclejdk8

branches:
  only:
    - feature/add-travis