env:
  - ORG_GRADLE_PROJECT_JAVA_8=$JAVA_HOME ORG_GRADLE_PROJECT_JAVA_11=openjdk11
addons:
  hosts:
    - localhost
language: java
install: true
jdk:
  - oraclejdk8
script:
  - export JAVA_8=$JAVA_HOME
  - export JAVA_11=$HOME/opejdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_11
  - ./gradlew build
branches:
  only:
    - feature/add-travis