addons:
  hosts:
    - localhost
language: java
install: true
dist: trusty
jdk: oraclejdk8
script:
  - export ORG_GRADLE_PROJECT_JAVA_8=$JAVA_HOME
  - export ORG_GRADLE_PROJECT_JAVA_11=`jdk_switcher.sh openjdk11`
  - ./gradlew build
branches:
  only:
    - master
