env:
  - ORG_GRADLE_PROJECT_JAVA_8=$JAVA_HOME ORG_GRADLE_PROJECT_JAVA_11=/home/travis/openjdk11
addons:
  hosts:
    - localhost
language: java
install: true
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
jdk:
  - oraclejdk8
script:
  - export JAVA_8=$JAVA_HOME
  - install-jdk.sh -F 11
  - export JAVA_11=$JAVA_HOME
  - ./gradlew build
branches:
  only:
    - feature/add-travis