env:
  - JAVA_7=openjdk7
  - JAVA_8=oraclejdk8
  - JAVA_9=oraclejdk9
  - JAVA_11=openjdk11
  global:
    - TIMEOUT=5000
addons:
  hosts:
    - localhost
language: java
install: true

script:
  - ./gradlew build
jdk:
  - oraclejdk8

branches:
  only:
    - feature/add-travis