addons:
  hosts:
    - localhost
language: java
install: true
jdk: openjdk11
script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - export ORG_GRADLE_PROJECT_JAVA_8=/usr/lib/jvm/java-8-oracle
  - export ORG_GRADLE_PROJECT_JAVA_11=$JAVA_HOME
  - export JAVA_HOME=$ORG_GRADLE_PROJECT_JAVA_11
  - ./gradlew build
branches:
  only:
    - master