env:
  - ORG_GRADLE_PROJECT_JAVA_8=$JAVA_HOME ORG_GRADLE_PROJECT_JAVA_11=/home/travis/jdk-11.0.1
addons:
  hosts:
    - localhost
language: java
install: true
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
matrix:
  include:
    - env: JDK='OpenJDK 11'
      install: . ./install-jdk.sh -F 11 -L GPL
jdk:
  - oraclejdk8
script:
  - export JAVA_8=$JAVA_HOME
  - export JAVA_11=/home/travis/jdk-11.0.1
  - ./gradlew build
branches:
  only:
    - feature/add-travis