env:
  - ORG_GRADLE_PROJECT_JAVA_8=/usr/lib/jvm/java-8-oracle ORG_GRADLE_PROJECT_JAVA_11=/usr/lib/jvm/java-11-oracle
addons:
  hosts:
    - localhost
language: java
install: true
script:
  - ./gradlew build
jdk:
  - oraclejdk8 oraclejdk11
branches:
  only:
    - feature/add-travis