addons:
  hosts:
    - localhost
language: java
install: true
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
matrix:
  include:
    - env: JDK='OpenJDK 11'
      install: . ./install-jdk.sh -F 11 -L GPL
jdk: oraclejdk8
script:
  - export ORG_GRADLE_PROJECT_JAVA_8=/usr/lib/jvm/java-8-oracle
  - export ORG_GRADLE_PROJECT_JAVA_11=/home/travis/jdk-11.0.1
  - export JAVA_HOME=$JAVA_8
  - echo $JAVA_HOME
  - echo $ORG_GRADLE_PROJECT_JAVA_8
  - echo $ORG_GRADLE_PROJECT_JAVA_11
  - ./gradlew build
branches:
  only:
    - feature/add-travis