env:
  - ORG_GRADLE_PROJECT_JAVA_8=openjdk8 ORG_GRADLE_PROJECT_JAVA_11=openjdk11
addons:
  hosts:
    - localhost
language: java
install: true
script:
  - ./gradlew build
jdk:
  - oraclejdk8
branches:
  only:
    - feature/add-travis