addons:
  hosts:
    - localhost
language: java
install: true
jdk: oraclejdk8
script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - ./install-jdk.sh -F 11 -L GPL
  - export ORG_GRADLE_PROJECT_JAVA_8=/usr/lib/jvm/java-8-oracle
  - export ORG_GRADLE_PROJECT_JAVA_11=/home/travis/jdk-11.0.1
  - export JAVA_HOME=$ORG_GRADLE_PROJECT_JAVA_8
  - echo $JAVA_HOME
  - echo $ORG_GRADLE_PROJECT_JAVA_8
  - echo $ORG_GRADLE_PROJECT_JAVA_11
  - java -version
  - ./gradlew -version -Dorg.gradle.java.home=$ORG_GRADLE_PROJECT_JAVA_8
  - ./gradlew build -Dorg.gradle.java.home=$ORG_GRADLE_PROJECT_JAVA_8
branches:
  only:
    - feature/add-travis