env:
  - ORG_GRADLE_PROJECT_JAVA_8=$JAVA_HOME ORG_GRADLE_PROJECT_JAVA_11=/usr/lib/jvm/java-11-oracle
addons:
  hosts:
    - localhost
language: java
install: true
jdk:
  - oraclejdk8
script:
  - export JAVA_8=$JAVA_HOME
  - export JAVA_11=/usr/lib/jvm/openjdk-11-jdk
  - ./gradlew build
branches:
  only:
    - feature/add-travis