env:
  - ORG_GRADLE_PROJECT_JAVA_8=$JAVA_HOME ORG_GRADLE_PROJECT_JAVA_11=openjdk11
addons:
  apt:
    packages:
      - oraclejdk11
  hosts:
    - localhost
language: java
install: true
jdk:
  - oraclejdk8
script:
  - export JAVA_8=oraclejdk8
  - export JAVA_11=opejdk11
  - ./gradlew build
branches:
  only:
    - feature/add-travis